---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nexshop
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        role: app
      containers:
        - name: frontend
          image: mabroukamessaoudi1/frontend:latest  # replaced by deploy.sh
          ports:
            - containerPort: 443
            - containerPort: 80
          env:
            - name: API_GATEWAY_URL
              value: "http://192.168.100.113:30900"
            - name: KEYCLOAK_URL
              value: "http://192.168.100.113:30818"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: tls-certs
              mountPath: /etc/nginx/certs
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
        - name: tls-certs
          secret:
            secretName: frontend-tls

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nexshop
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30200
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30201  # just for the HTTP→HTTPS redirect
