---
# ── MySQL credentials ─────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nexshop
type: Opaque
stringData:
  root-password: "mysql"
  order-db: "order_service"
  inventory-db: "inventory_service"
---
# ── MongoDB credentials ───────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: nexshop
type: Opaque
stringData:
  root-username: "root"
  root-password: "password"
  database: "product-service"
---
# ── Keycloak credentials ──────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: nexshop
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "admin"
  db-user: "keycloak"
  db-password: "password"
---
# ── Mail credentials (Gmail App Password) ────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: nexshop
type: Opaque
stringData:
  username: "***REMOVED***"
  password: "***REMOVED***"
---
# ── Global ConfigMap ──────────────────────────────────────────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexshop-config
  namespace: nexshop
data:
  # Service URLs (Kubernetes internal DNS)
  INVENTORY_URL: "http://inventory-service:8082"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8085"
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/spring-microservices-security-realm"
  KEYCLOAK_JWK_URI: "http://keycloak:8080/realms/spring-microservices-security-realm/protocol/openid-connect/certs"
  ZIPKIN_ENDPOINT: "http://tempo:9411/api/v2/spans"
  LOKI_URL: "http://loki.monitoring:3100/loki/api/v1/push"
  # Product service
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8081"
