apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: nexshop
data:
  nginx.conf: |
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate     /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        root /usr/share/nginx/html;
        index index.html;

        add_header Cross-Origin-Opener-Policy "same-origin" always;
        add_header Cross-Origin-Embedder-Policy "require-corp" always;

        location /env.js {
            root /usr/share/nginx/html;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /health {
            return 200 "ok";
            add_header Content-Type text/plain;
        }
    }

    server {
        listen 80;
        server_name _;
        return 301 https://$host:30200$request_uri;
    }
